namespace Shared.Contracts;

// ---------------------------------------------------------------------------
// Message contracts shared between TopUp.Api and Wallet.Api.
//
// Two kinds of message in MassTransit:
//   COMMANDS  — "do this" (sent to ONE known consumer).      e.g. DebitWallet
//   EVENTS    — "this happened" (published; 0..n subscribers). e.g. WalletDebited
//
// The TopUpId is the SAGA correlation id: every message in one top-up flow
// carries the same TopUpId so MassTransit routes it back to the same saga
// instance. The IdempotencyKey is passed through to the Wallet so the actual
// money move is still exactly-once even if a command is redelivered.
// ---------------------------------------------------------------------------

// ----- Command that starts the saga (API endpoint -> saga) -----

/// <summary>Kick off a top-up flow. Published by the HTTP endpoint; creates the
/// saga instance. TopUpId is generated by the endpoint and is the correlation id
/// for the whole flow.</summary>
public record StartTopUp(
    Guid TopUpId,
    Guid AccountId,
    string UserId,            // the authenticated caller (JWT sub), carried for the ownership check
    string PhoneNumber,
    decimal Amount,
    string IdempotencyKey);

// ----- Commands (TopUp -> Wallet) -----

/// <summary>Tell the Wallet service to debit funds for a top-up. Carries the
/// requesting UserId so the Wallet can verify the account belongs to that user
/// (ownership check on the internal path too, not just the HTTP edge).</summary>
public record DebitWallet(
    Guid TopUpId,
    Guid AccountId,
    string UserId,
    decimal Amount,
    string IdempotencyKey);

/// <summary>Compensating command: refund a debit that was already applied,
/// because a later step (the operator charge) failed. This is the saga's
/// "undo" — we never physically roll back the committed debit; we post an
/// equal, opposite credit so the ledger stays append-only and auditable.</summary>
public record RefundWallet(
    Guid TopUpId,
    Guid AccountId,
    decimal Amount,
    string IdempotencyKey);

// ----- Events (Wallet -> TopUp) -----

/// <summary>Wallet debit committed successfully.</summary>
public record WalletDebited(
    Guid TopUpId,
    Guid AccountId,
    decimal Amount,
    Guid TransactionId);

/// <summary>Wallet debit rejected (e.g. insufficient funds, account missing).</summary>
public record WalletDebitFailed(
    Guid TopUpId,
    Guid AccountId,
    string Reason);

/// <summary>Compensating refund committed — the saga can now finish as Refunded.</summary>
public record WalletRefunded(
    Guid TopUpId,
    Guid AccountId,
    decimal Amount,
    Guid TransactionId);
